spring:
  application:
    name: consumer-service

  kafka:
    bootstrap-servers: localhost:19092

    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      enable-auto-commit: false

    listener:
      ack-mode: manual_immediate

  datasource:
    url: jdbc:postgresql://localhost:5433/event_platform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081