spring:
  application:
    name: producer-service

  kafka:
    bootstrap-servers: localhost:19092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        retries: 2147483647
        max.in.flight.requests.per.connection: 5

  datasource:
    url: jdbc:postgresql://localhost:5433/event_platform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}